//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolunteerHub.Pages.SuperAdmin
{
    public partial class Dashboard
    {
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl statWorkspaces;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl statAdmins;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl statVolunteers;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl statProjects;
        protected global::System.Web.UI.WebControls.GridView gvWorkspaces;
    }
}
