//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolunteerHub.Pages.SuperAdmin
{
    public partial class EditWorkspace
    {
        protected global::System.Web.UI.WebControls.Literal litAlert;
        protected global::System.Web.UI.WebControls.HiddenField hfId;
        protected global::System.Web.UI.WebControls.TextBox txtName;
        protected global::System.Web.UI.WebControls.TextBox txtCode;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl currentLogo;
        protected global::System.Web.UI.WebControls.FileUpload fuLogo;
        protected global::System.Web.UI.WebControls.CheckBox chkActive;
        protected global::System.Web.UI.WebControls.Button btnSave;
    }
}
