//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolunteerHub.Pages.SuperAdmin
{
    public partial class WorkspaceDetail
    {
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl breadcrumbName;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pageTitle;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pageSubtitle;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl statVolunteers;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl statProjects;
        protected global::System.Web.UI.WebControls.GridView gvAdmins;
        protected global::System.Web.UI.WebControls.GridView gvVolunteers;
    }
}
