//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolunteerHub.Pages
{
    public partial class Error
    {
        protected global::System.Web.UI.WebControls.Literal litError;
    }
}
