//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolunteerHub
{
    public partial class DashboardMaster
    {
        protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl sidebarOverlay;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl vhSidebar;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl sidebarRoleLabel;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl navSuperAdmin;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl navAdmin;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl navVolunteer;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl topbarAvatar;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl topbarName;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl topbarRole;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder BreadcrumbContent;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder ScriptContent;
    }
}
