//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolunteerHub.Pages.Volunteer
{
    public partial class Dashboard
    {
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl greeting;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl statHours;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl statProjects;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl statEvents;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl statCompleted;
        protected global::System.Web.UI.WebControls.Repeater rptProjects;
        protected global::System.Web.UI.WebControls.GridView gvEvents;
        protected global::System.Web.UI.WebControls.Literal litChartScript;
    }
}
