//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolunteerHub.Pages.Volunteer
{
    public partial class EditEvent
    {
        protected global::System.Web.UI.WebControls.Literal litAlert;
        protected global::System.Web.UI.WebControls.HiddenField hfId;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblProject;
        protected global::System.Web.UI.WebControls.TextBox txtDate;
        protected global::System.Web.UI.WebControls.TextBox txtStartTime;
        protected global::System.Web.UI.WebControls.TextBox txtEndTime;
        protected global::System.Web.UI.WebControls.TextBox txtHours;
        protected global::System.Web.UI.WebControls.TextBox txtNotes;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl existingPhotosSection;
        protected global::System.Web.UI.WebControls.HiddenField hfDeleteImageIds;
        protected global::System.Web.UI.WebControls.Repeater rptExistingImages;
        protected global::System.Web.UI.WebControls.Button btnSave;
    }
}
