//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolunteerHub.Pages.Volunteer
{
    public partial class MyEvents
    {
        protected global::System.Web.UI.WebControls.Literal litAlert;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl statTotal;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl statCount;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl statAvg;
        protected global::System.Web.UI.WebControls.GridView gvEvents;
    }
}
