//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolunteerHub.Pages.Volunteer
{
    public partial class MyProjects
    {
        protected global::System.Web.UI.WebControls.Repeater rptProjects;
    }
}
