//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolunteerHub.Pages.Volunteer
{
    public partial class Profile
    {
        protected global::System.Web.UI.WebControls.Literal litAlert;
        protected global::System.Web.UI.WebControls.TextBox txtFirstName;
        protected global::System.Web.UI.WebControls.TextBox txtLastName;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.TextBox txtPhone;
        protected global::System.Web.UI.WebControls.TextBox txtDob;
        protected global::System.Web.UI.WebControls.TextBox txtAddress;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl currentAvatarText;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl currentAvatarImg;
        protected global::System.Web.UI.WebControls.FileUpload fuPhoto;
        protected global::System.Web.UI.WebControls.Button btnSaveProfile;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl statHours;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl statProjects;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl statJoined;
        protected global::System.Web.UI.WebControls.TextBox txtCurrentPwd;
        protected global::System.Web.UI.WebControls.TextBox txtNewPwd;
        protected global::System.Web.UI.WebControls.TextBox txtConfirmPwd;
        protected global::System.Web.UI.WebControls.Button btnChangePwd;
    }
}
