//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolunteerHub.Pages.Volunteer
{
    public partial class ProjectDetail
    {
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl breadcrumbTitle;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pageTitle;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pageMeta;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl statusBadge;
        protected global::System.Web.UI.WebControls.Button btnJoin;
        protected global::System.Web.UI.WebControls.Literal litAlert;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl descCard;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl descText;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl myHoursCard;
        protected global::System.Web.UI.WebControls.GridView gvMyEvents;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl infoStart;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl infoEnd;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl infoLocRow;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl infoLoc;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl infoHrsRow;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl infoHrs;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl infoMaxRow;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl infoMax;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl progressCard;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl progressLabel;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl progressPct;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl progressBar;
    }
}
