//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolunteerHub.Pages.Admin
{
    public partial class CreateProject
    {
        protected global::System.Web.UI.WebControls.Literal litAlert;
        protected global::System.Web.UI.WebControls.TextBox txtTitle;
        protected global::System.Web.UI.WebControls.TextBox txtDescription;
        protected global::System.Web.UI.WebControls.TextBox txtLocation;
        protected global::System.Web.UI.WebControls.TextBox txtStartDate;
        protected global::System.Web.UI.WebControls.TextBox txtEndDate;
        protected global::System.Web.UI.WebControls.TextBox txtMaxVols;
        protected global::System.Web.UI.WebControls.TextBox txtHoursRequired;
        protected global::System.Web.UI.WebControls.Button btnSave;
    }
}
