//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolunteerHub.Pages.Admin
{
    public partial class Dashboard
    {
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl wsSubtitle;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl statProjects;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl statVolunteers;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl statHours;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl statActive;
        protected global::System.Web.UI.WebControls.GridView gvProjects;
        protected global::System.Web.UI.WebControls.Literal litChartScript;
    }
}
