//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolunteerHub.Pages.Admin
{
    public partial class Projects
    {
        protected global::System.Web.UI.WebControls.Literal litAlert;
        protected global::System.Web.UI.WebControls.GridView gvProjects;
    }
}
