//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolunteerHub.Pages.Admin
{
    public partial class ProjectDetail
    {
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl breadcrumbTitle;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pageTitle;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pageMeta;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl statEnrolled;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl statTotalHours;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl statDaysLeft;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl descriptionCard;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl descriptionText;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkExportExcel;
        protected global::System.Web.UI.WebControls.GridView gvVolunteers;
    }
}
