//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolunteerHub.Pages.Admin
{
    public partial class Volunteers
    {
        protected global::System.Web.UI.WebControls.GridView gvVolunteers;
    }
}
