//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolunteerHub.Pages.Admin
{
    public partial class VolunteerProjectEvents
    {
        protected global::System.Web.UI.WebControls.HyperLink breadcrumbProject;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl breadcrumbVolunteer;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pageTitle;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pageMeta;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl statHours;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl statCount;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl statPhotos;
        protected global::System.Web.UI.WebControls.GridView gvEvents;
    }
}
